# Generated by Django 3.2.15 on 2022-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
