# Generated by Django 3.2.15 on 2022-11-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_alter_projectcharter_id'),
        ('events', '0004_venue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget_app.projectcharter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.projectcharter')),
            ],
        ),
    ]
