# Generated by Django 3.2.15 on 2022-11-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221109_2219'),
    ]

    operations = [
    ]
