# Generated by Django 3.2.15 on 2022-11-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_all_day_event_allday'),
    ]

    operations = [
    ]
