# Generated by Django 3.2.15 on 2022-11-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20221112_1218'),
        ('events', '0011_event_eventclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.status'),
            preserve_default=False,
        ),
    ]
