# Generated by Django 3.2.15 on 2022-11-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_app', '0003_alter_projectcharter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('wbs', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('time', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('work', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Predecesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=15, default=0, max_digits=19)),
                ('type', models.CharField(max_length=2)),
                ('name', models.ManyToManyField(null=True, to='activities.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='Predecessor',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Predecesor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.projectcharter'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.status'),
        ),
    ]
