# Generated by Django 3.2.15 on 2022-11-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20221111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sch_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
