# Generated by Django 3.2.15 on 2022-11-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_predecessor_activity_predecessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='finish_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='sch_finish_date',
            new_name='sch_end_Date',
        ),
    ]
