# Generated by Django 3.2.15 on 2022-11-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20221112_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='action',
        ),
    ]
