# Generated by Django 3.2.15 on 2022-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_activity_activity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
