# Generated by Django 3.2.15 on 2022-10-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FY_name', models.CharField(max_length=20)),
                ('FY_start_date', models.DateField(verbose_name='FY Start Date')),
                ('FY_end_date', models.DateField(verbose_name='FY End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fixed_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScopeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('items', models.ManyToManyField(to='budget_app.ScopeItem')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(blank=True, max_length=20, null=True)),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Schedule Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Schedule End Date')),
                ('fiscalyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.fiscalyear')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sponsor', models.CharField(max_length=30)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.budget')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.schedule')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.scopestatement')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(to='budget_app.ProjectCharter')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('expense_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.costtype')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='items',
            field=models.ManyToManyField(to='budget_app.BudgetItem'),
        ),
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.fiscalyear')),
                ('program', models.ManyToManyField(to='budget_app.Program')),
            ],
        ),
    ]
