# Generated by Django 3.2.15 on 2022-11-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='fiscalyear',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='budget_app.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarter',
            name='quarter_enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Quarter end date'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='quarter_start',
            field=models.DateField(blank=True, null=True, verbose_name='Quarter start date'),
        ),
    ]
