# Generated by Django 3.2.15 on 2022-11-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20221105_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcharter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
