# Generated by Django 3.2.15 on 2022-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_alter_projectcharter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcharter',
            name='organization',
            field=models.CharField(default='Northwestern', max_length=30),
        ),
    ]
