# Generated by Django 3.2.15 on 2022-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
