# Generated by Django 3.2.15 on 2022-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_delete_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='event_name',
            field=models.CharField(default='Previous Event', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseinfo',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
