# Generated by Django 3.2.15 on 2022-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_auto_20221021_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_name', models.CharField(max_length=20)),
                ('quarter_startdate', models.CharField(max_length=20)),
            ],
        ),
    ]
