# Generated by Django 3.2.15 on 2022-10-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_expenseinfo_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='quarter',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
    ]
