# Generated by Django 3.2.15 on 2022-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_auto_20221021_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
