# Generated by Django 3.2.15 on 2022-10-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_navbar_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='navbar_item',
        ),
    ]
