# Generated by Django 3.2.15 on 2022-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0013_fiscalyear_quarter_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='FY_end_date',
            field=models.DateField(verbose_name='FY End Date'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='FY_start_date',
            field=models.DateField(verbose_name='FY Start Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(verbose_name='Schedule End Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(verbose_name='Schedule Start Date'),
        ),
    ]
