# Generated by Django 3.2.15 on 2022-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0014_auto_20221022_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Schedule End Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Schedule Start Date'),
        ),
    ]
