# Generated by Django 3.2.15 on 2022-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0017_schedule_schedule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fixed_cost', models.IntegerField()),
                ('variable_cost', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('items', models.ManyToManyField(to='budget_app.ScopeItem')),
            ],
        ),
    ]
