# Generated by Django 3.2.15 on 2022-10-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0019_auto_20221022_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeitem',
            name='description',
            field=models.TextField(),
        ),
    ]
