# Generated by Django 3.2.15 on 2022-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0020_alter_scopeitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopestatement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopestatement',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
