# Generated by Django 3.2.15 on 2022-10-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0022_budget_budgetitem_costtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetitem',
            old_name='costtype',
            new_name='cost_type',
        ),
    ]
