# Generated by Django 3.2.15 on 2022-10-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0023_rename_costtype_budgetitem_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.costtype'),
        ),
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sponsor', models.CharField(max_length=30)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.budget')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.schedule')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.scopestatement')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(to='budget_app.ProjectCharter')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_app.fiscalyear')),
                ('program', models.ManyToManyField(to='budget_app.Program')),
            ],
        ),
    ]
