# Generated by Django 3.2.15 on 2022-11-20 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('msGraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookAgenda',
            fields=[
                ('agenda_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='events.agenda_item')),
                ('outlook_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('change_key', models.CharField(max_length=128)),
                ('organizer', models.CharField(max_length=128)),
                ('show_as', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.agenda_item',),
        ),
    ]
