# Generated by Django 4.1 on 2022-11-20 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msGraph', '0002_outlookagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlookevent',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outlookevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
