# Generated by Django 4.1 on 2022-11-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msGraph', '0003_alter_outlookevent_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutlookAgenda',
        ),
    ]
